version: '2'

services:

  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    restart: always
    links:
      - db:db_domain
    depends_on:
      - db



  db:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=common
