version: '3.9'

services:

  app:
    container_name: cucumber-app
    build: .
    restart: always
    links:
      - db:db_domain
    depends_on:
      - db
    networks:
      - cucumber-backend
    ports:
      - 8000:8000

  db:
    container_name: cucumber-db
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=common
    # volumes:
    #   - cucumber-db-storage:/var/lib/postgresql/data
    networks:
      - cucumber-backend
    ports:
      - 5432:5432

  adminer:
    image: adminer
    links:
      - db:db_domain
    depends_on:
      - db
    networks:
      - cucumber-backend
    ports:
      - 8080:8080

volumes:
  cucumber-db-storage:

networks:
  cucumber-backend:
    driver: bridge
