"""”Init”

Revision ID: 405673c798a3
Revises: 
Create Date: 2021-07-14 02:44:51.641250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405673c798a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False)
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk__categories'))
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk__clients'))
    )
    op.create_table('order_list',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk__order_list'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk__orders'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk__products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('order_list')
    op.drop_table('clients')
    op.drop_table('categories')
    op.drop_table('addresses')
    # ### end Alembic commands ###
