"""”Init”

Revision ID: e978a7ceeb9d
Revises: 
Create Date: 2021-07-25 17:10:51.752178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e978a7ceeb9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('validation', sa.Boolean(), nullable=True))
    op.drop_column('clients', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('clients', 'validation')
    # ### end Alembic commands ###
